#List of worlds where lucky blocks will be enabled.
Worlds-list:
- world
Wands:
  Regen:
    cooldown-time: 20
    required-permission: false
    permission: amazinglb.wands.regenwand
    limited-uses:
        enable: false
        uses: 5
  Dragon-breath:
    cooldown-time: 20
    required-permission: false
    permission: amazinglb.wands.dragonbreathwand
    limited-uses:
        enable: false
        uses: 5
  Invisibility:
    cooldown-time: 20
    required-permission: false
    permission: amazinglb.wands.invwand
    limited-uses:
        enable: false
        uses: 5
  TNT:
    cooldown-time: 20
    required-permission: false
    permission: amazinglb.wands.tntwand
    limited-uses:
        enable: false
        uses: 5
  Slime:
    cooldown-time: 20
    required-permission: false
    permission: amazinglb.wands.slimewand
    limited-uses:
        enable: false
        uses: 5
  Lightning:
    cooldown-time: 20
    required-permission: false
    permission: amazinglb.wands.lightning
    limited-uses:
        enable: false
        uses: 5
  Shield:
    cooldown-time: 20
    ShieldWandBlock: 'LEAVES'
    withfloor: true
    required-permission: false
    permission: amazinglb.wands.shield
    limited-uses:
        enable: false
        uses: 5
Objects:
  DarkHole:
    number-of-blocks: 5
    #The time must be in ticks. 1 second = 20 ticks
    time-before-darkhole: 20
    #The time must be in ticks. 1 second = 20 ticks
    time-between-one-block-and-the-next: 5
    block-material: BUCKET
    required-permission: false
    permission: amazinglb.objets.darkhole
  MiniVolcano:
    #The time must be in ticks. 1 second = 20 ticks
    time-before-minivolcano: 20
    #The time must be in ticks. 1 second = 20 ticks
    time-between-one-block-and-the-next: 20
    block-material: LAVA_BUCKET
    required-permission: false
    permission: amazinglb.objets.minivolcano
  IceBow:
    freeze-material: ICE
    required-permission: false
    permission: amazinglb.objects.icebow
Commands:
    Update-message-permission: amazinglb.update
    Reload-permission: amazinglb.reload
    Give:
        Wands: amazinglb.give.wands
        Objects: amazinglb.give.objects
        LuckyBlock: amazinglb.give.luckyblock
    RandomBlocks-permission: amazinglb.randomblocks
Update-checker: true
LuckyBlock:
    Name: '&6&lLuckyBlock'
    Material: 'SPONGE'
