name: NewAmazingLuckyBlocks
main: net.servermc.plugins.AmazingLuckyBlocks
version: 1.5.0 BETA
description: The Official LuckyBlocks plugin of ServerMC.
author: RewKun
commands:
   alb:
    description: The main command of New Amazing Lucky Blocks.
softdepend: [Multiverse-Core, HeadDatabase]
