name: NewAmazingLuckyBlocks
main: net.servermc.plugins.AmazingLuckyBlocks
version: 1.2.5 BETA
description: The Official LuckyBlocks plugin of ServerMC.
author: RewKun
commands:
   alb:
    description: Reload config and lang files of New Amazing Lucky Blocks.
    usage: /alb [args]
